version: "3.8"

services:
  # Webový server s PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    command: bash -c 'docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground'

  # MySQL databáze
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mojeheslo
      - MYSQL_DATABASE=mojedatabaze
      - MYSQL_USER=uzivatel
      - MYSQL_PASSWORD=heslo
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
